export const STOCKS_SET_STOCK = 'STOCKS_SET_STOCK';
export const STOCKS_DELETE_STOCK = 'STOCKS_DELETE_STOCK';
export const STOCKS_SET_ERROR = 'STOCKS_SET_ERROR';
export const STOCKS_CLEAR_ERROR = 'STOCKS_CLEAR_ERROR';
export const STOCKS_SET_LOADING = 'STOCKS_SET_LOADING';
